### ISSUE TITLE
Consecutive operations does not work

### ISSUE THREAD

**Issue by ndyashas** [utthamtejaswi/diy_caliculator#1]
After finishing one calculation. One is unable to perform another calculation. The "number1" remains zero while "number2" is assigned its corresponding value. Please have a look at the image.

```
yashas@Jalashwa:/tmp/diy_caliculator$ python3 diy_caliculator.py 
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
1 + 3
4
0 - 6
-6
```

In the second operation, I had entered '5 - 6' but it took '0 - 6'.

**Comment by utthamtejaswi** [comment]
will be fixed in a movement.

**Comment by utthamtejaswi** [comment]
will be fixed in a moment

**Comment by utthamtejaswi** [comment]
problem fixed.
