### ISSUE TITLE
Real time display of the current equation

### ISSUE THREAD

**Issue by ndyashas** [utthamtejaswi/diy_caliculator#3]
When one wants to calculate say `5 - 6`, the inputs are not shown in the bottom screen while entering them. This would be a very useful feature to have in the program.

**Comment by utthamtejaswi** [comment]
it is solved .
thankyou

**Comment by ndyashas** [comment]
The problem has not been fully solved. The equation is not visible when one is typing it out

**Comment by utthamtejaswi** [comment]
will be solved

**Comment by utthamtejaswi** [comment]
this is now completely solved, check out the new commit .
